# Generated by Django 5.0.6 on 2024-06-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddh', '0002_user_pack_days_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pack_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
