# Generated by Django 5.0.6 on 2024-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddh', '0003_pack_pack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='channelty',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
